# Generated by Django 2.0.5 on 2018-05-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
