# Generated by Django 2.0.5 on 2018-05-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0003_auto_20180524_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
    ]
